### ISSUE TITLE
US27-T01 Testes de aceitação do cadastro de medicamentos (definição)

### ISSUE THREAD

**Issue by overmanniac** [stagiopbd/ipbl2019#104]
Criação dos casos de teste para a US27, associada ao cadastro de medicamentos que deve ser construído nessa Sprint. Essa tarefa de criação de casos testes envolve todos os possíveis níveis associados à essa US (banco de dados, front-end, back-end) quando existirem.

**Comment by eduardohem** [comment]
Tabela de testes confeccionada conforme requisitos de aceitação. Disponível no drive.
