### ISSUE TITLE
US27-T02 Testes de aceitação do cadastro de medicamentos (execução)

### ISSUE THREAD

**Issue by overmanniac** [stagiopbd/ipbl2019#105]
Execução dos casos de teste para a US27, associada ao cadastro de medicamentos que deve ser construído nessa Sprint. Essa tarefa de execução de casos testes envolve todos os possíveis níveis associados à essa US (banco de dados, front-end, back-end) quando existirem - e DEPENDE da US27-T01.

**Comment by eduardohem** [comment]
Testes executados conforme. Todos os campos acertados em reunião foram conferidos e presentes.
