### ISSUE TITLE
US110-T01 Testes de aceitação do mecanismo "consumidor" de dados da parte de Fornecedores para Kafka (definição)

### ISSUE THREAD

**Issue by overmanniac** [stagiopbd/ipbl2019#110]
Criação dos casos de teste para a US110, associada ao mecanismo "consumidor" de dados que deverá ser construído nessa Sprint e que receberá dados do barramento Kafka e armazenará na base de conhecimento compartilhada (que será MongoDB, MySQL ou outro). Essa tarefa de criação de casos testes envolve todos os possíveis níveis associados à essa US (banco de dados, front-end, back-end) quando existirem.

**Comment by eduardohem** [comment]
Confeccionada a definição dos testes, conforme os requisitos.
