### ISSUE TITLE
US27-T09 Criar view apenas para consulta dos medicamentos cadastrados

### ISSUE THREAD

**Issue by hdblouro** [stagiopbd/ipbl2019#120]
A rotina deverá listar os medicamentos cadastrados e ser capaz de aplicar filtros sobre a descrição do medicamento, fabricante, classe terapêutica, tipo de produto e tarja.
Deverá ser possível visualizar todas as informações de cada medicamento.

**Comment by overmanniac** [comment]
Uma primeira versão da view foi criada! Está aqui no GitHub, na branch "development_us27".  No momento a view já lista os medicamentos cadastrados, mas falta implementar a parte de filtros solicitada na tarefa. Também pode ser alterado as informações que são mostradas, pois se for mostrar tudo pode não caber na tela, então deixei exibindo algumas que considerei principais.

**Comment by overmanniac** [comment]
Agora a view já tem um filtro simples de tarja e ainda tem um campo de busca por descrição do medicamento. Com isso acredito que já atenda os requisitos de completude, por isso irei passar para feito.
O código mais recente já foi commitado.
