### ISSUE TITLE
US27-T07 Converter o Modelo Lógico das tabelas para o BD físico

### ISSUE THREAD

**Issue by hdblouro** [stagiopbd/ipbl2019#121]
Converter os modelos lógicos das tabelas criadas nessa US para o BD físico.

**Comment by hdblouro** [comment]
Modelo transferido para o banco físico local e online.
[STAGIOP-BD.zip](https://github.com/stagiopbd/ipbl2019/files/3117976/STAGIOP-BD.zip)

**Comment by hdblouro** [comment]
Dados para acesso ao BD online:
IP Servidor: 169.57.166.143
Porta: 3306
Banco: logic685_stagiopbd
Usuário: times04
Senha: times042019#
Usuário com todos os privilégios

**Comment by overmanniac** [comment]
Victor Pugliese solicitou uma correção - mudar de "people" para "person".
[STAGIOP-BD_Fornecedor.zip](https://github.com/stagiopbd/ipbl2019/files/3119312/STAGIOP-BD_Fornecedor.zip)

**Comment by overmanniac** [comment]
ATENÇÃO:
Os dados corretos de acesso são os seguintes.
Usuário: logic685_times04
Senha: TimeS042019
IP: 169.57.166.143
Porta: 3306

**Comment by overmanniac** [comment]
Uma informação adicional: com esse .SQL e modelos já pude criar todas as migrations (o que cria a estrutura da tabela no PHP) e seeds (o que carrega os dados das tabelas no PHP). Verificar o código que está na branch "development_us27" pois já contempla essas alterações.
