### ISSUE TITLE
#US116#TSK6 [0/3] - Testar os relacionamentos com as demais entidades e garantir a integridades entre elas

### ISSUE THREAD

**Issue by gleme** [stagiopbd/ipbl2019#169]

**Comment by josejuniorcj** [comment]
Relacionamento verifirado atraves do MER e disponibilizado MER atualizado no google drive > https://drive.google.com/file/d/1X1ImVQ-3Z2mzAQ1nS5l4NhZMxOU99M74/view?usp=sharing
