### ISSUE TITLE
[US27-T10] Correção trigramação das tabelas Tipo_Fornecedor e Fornecedor para o modelo padrão.

### ISSUE THREAD

**Issue by marcilenne** [stagiopbd/ipbl2019#173]
Solicitado pelo SM alteração da trigramação para um padrão em inglês nomes das tabelas e colunas.

**Comment by hdblouro** [comment]
Apenas uma correção, isso foi solicitação dos POs. Apenas transmiti a informação. Está registrado em ATA e no vídeo.

**Comment by hdblouro** [comment]
Modelo importado do BD online.

[Modelo BD Fornecedor.zip](https://github.com/stagiopbd/ipbl2019/files/3112487/Modelo.BD.Fornecedor.zip)

**Comment by hdblouro** [comment]
Modelo traduzido e trigramado,
[Modelo BD Fornecedor.zip](https://github.com/stagiopbd/ipbl2019/files/3112526/Modelo.BD.Fornecedor.zip)
