### ISSUE TITLE
US110-T03 Desenvolver uma aplicação "consumidor" em PHP/Python/outra linguagem para consumir os dados de FORNECEDOR no KAFKA

### ISSUE THREAD

**Issue by overmanniac** [stagiopbd/ipbl2019#182]
Desenvolver uma aplicação em PHP/Python/outra linguagem para consumir no KAFKA os dados do FORNECEDOR e armazenar em banco de dados MySQL compartilhado (base de conhecimento compartilhada). Não precisa, e provavelmente não estará, integrada à aplicação de cadastro de fornecedores desenvolvida na Sprint 1.

**Comment by thiagocardoso1988** [comment]
base para consumo de mensagens de medicamentos criada
