### ISSUE TITLE
US25-T01 Criar a classe que faz conexão com o banco de dados

### ISSUE THREAD

**Issue by kauezanetti** [stagiopbd/ipbl2019#22]
O objetivo dessa tarefa é a implementação da classe de conexão com o banco de dados.

**Comment by overmanniac** [comment]
Foi criado um código em PHP utilizando Laravel que faz a conexão com o banco de dados por meio de um modelo MVC e utilizando os mecanismos de conexão com o banco do próprio Laravel. Foi verificado que está funcionando corretamente, para as operações básicas realizadas.
