### ISSUE TITLE
US25-T02 Criar a classe que realiza as transações CRUD

### ISSUE THREAD

**Issue by kauezanetti** [stagiopbd/ipbl2019#23]
O objetivo dessa tarefa é desenvolver a classe responsável pelas transações CRUD.

**Comment by overmanniac** [comment]
Foi criado um código em PHP utilizando Laravel que faz as transações CRUD. Na verdade isso corresponde ao Controller do modelo MVC no qual o Laravel se baseia, e dentro desse Controller foram adicionadas todas as funções necessárias para o CRUD.
