### ISSUE TITLE
US25-T03 Criar os casos de testes (unitários) da classe que faz conexão com o banco de dados

### ISSUE THREAD

**Issue by kauezanetti** [stagiopbd/ipbl2019#24]

**Comment by kauezanetti** [comment]
O objetivo dessa tarefa é implementar e executar os testes unitário referente a classe que faz conexão com o banco de dados.

**Comment by overmanniac** [comment]
Durante a implementação foram testadas as principais funcionalidades do código implementado, e para o que ele se propõe inicialmente (cadastro de fornecedores) aparenta estar OK. Em futuras Sprints esse código será revisado e melhorado.
