### ISSUE TITLE
US25-T04 Criar os casos de teste (unitários) da classe que realiza as transações CRUD

### ISSUE THREAD

**Issue by kauezanetti** [stagiopbd/ipbl2019#25]

**Comment by kauezanetti** [comment]
O objetivo dessa tarefa é implementar e executar os testes unitário referente a classe responsável pelas transações CRUD.

**Comment by overmanniac** [comment]
Durante a implementação foram testadas as principais funcionalidades do código implementado, e para o que ele se propõe inicialmente (cadastro de fornecedores) aparenta estar OK. Em futuras Sprints esse código será revisado e melhorado.
