### ISSUE TITLE
US25-T05 Documentar as classes desenvolvidas para US25

### ISSUE THREAD

**Issue by kauezanetti** [stagiopbd/ipbl2019#26]
O objetivo dessa tarefa é documentar o código das classes desenvolvidas na US25

**Comment by overmanniac** [comment]
Na minha visão acho que não dará tempo para essa Sprint. Se considerar comentários no código como documentação, então acho que já está feito.

**Comment by overmanniac** [comment]
[Documento_Sintético_das_Classes_TS4_Sprint01.docx](https://github.com/stagiopbd/ipbl2019/files/3065436/Documento_Sintetico_das_Classes_TS4_Sprint01.docx)

Um primeiro documento resumido com essa documentação foi confeccionado. Nas próximas Sprints isso será melhorado, e a ideia é ao final termos um manual completo do sistema que está sendo desenvolvido.
