### ISSUE TITLE
#US05#TSK2 [3/3] - Definição dos dados que comporão o cadastro de consultas

### ISSUE THREAD

**Issue by miquelangelodias** [stagiopbd/ipbl2019#47]
Revisão

- [ ] Generalizar as entidades de médico e paciente separando pelo atributo CRM

- [ ] 3FN para as classificações dos capítulos de procedimentos
- [ ] Retirar updatedAt da consulta
- [ ] Verificar com o time de fornecedores a rastreabilidade dos medicamentos da consulta
 - [ ] Atrelar a chave do médico na consulta ao CRM

**Comment by gleme** [comment]
@Breslei @josejuniorcj criei um diagrama inicial da definição dos dados de consultas e procedimentos.
Os procedimentos eu fiz com base na CBHPM de 2016, coloquei um pdf com os dados lá e um doc com as definições, poderiam dar uma revisada e feedback?
Diagrama DB: https://dbdiagram.io/d/5ca0e1cff7c5bb70c72f7682
Documento das Definições de Dados: https://docs.google.com/document/d/1ttiY8cgRalyViyjGWoMLSbCog8BCIUdvOs4P7TRXtnI/edit?usp=sharing
