### ISSUE TITLE
US24-T02 Criar a view que lista os fornecedores cadastrados no banco de dados

### ISSUE THREAD

**Issue by overmanniac** [stagiopbd/ipbl2019#61]

**Comment by hdblouro** [comment]
Proposta de Wireframe da View com a lista de Fornecedores Cadastrados.
[Wireframe Fornecedores View.pdf](https://github.com/stagiopbd/ipbl2019/files/3041074/Wireframe.Fornecedores.View.pdf)

**Comment by hdblouro** [comment]
Atualização do Wireframe da lista de Fornecedores.
[Wireframe Fornecedores View.pdf](https://github.com/stagiopbd/ipbl2019/files/3047906/Wireframe.Fornecedores.View.pdf)

**Comment by overmanniac** [comment]
Da mesma forma que na view de CRUD, foi criada a view que lista os fornecedores. O modelo visual não foi exatamente o mesmo do Wireframe acima, porém muito semelhante. Nessa lista aparecem os principais dados do fornecedor, e foram feitos alguns testes (deletar fornecedor, verificar se ele não aparece mais na lista) e no que pudemos perceber está OK.
