### ISSUE TITLE
#US021 -  Instalação MySql Server (2)

### ISSUE THREAD

**Issue by leonardo-sguimaraes** [stagiopbd/ipbl2019#71]
Instalar localmente Mysql para uso de desenvolvimento.

**Comment by LexDias** [comment]
MySQL instalado

**Comment by jcpribeiro** [comment]
MySQL instalado

**Comment by LexDias** [comment]
Seguem SQLs para popular as tabelas 'hospital', 'hospital-situation', 'bed' e 'bed_type';


[stagiop.hospital.txt](https://github.com/stagiopbd/ipbl2019/files/3023892/stagiop.hospital.txt)
[stagiop.bed.txt](https://github.com/stagiopbd/ipbl2019/files/3023893/stagiop.bed.txt)
