### ISSUE TITLE
#US021 -  Instalação do NodeJs (2)

### ISSUE THREAD

**Issue by leonardo-sguimaraes** [stagiopbd/ipbl2019#72]
Instalar  NodeJs no ambiente local para uso no desenvolvimento.

**Comment by leonardo-sguimaraes** [comment]
Instalação do NodeJs realizada.  Utilizando a Versão : v8.10.0

**Comment by LexDias** [comment]
NodeJS instalado

**Comment by jcpribeiro** [comment]
NodeJS instalado
